// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIokGvom38yovmGozDiidr5RtOOomZ2is',
    appId: '1:511226301219:web:2b5a87535a0e18b3b51a96',
    messagingSenderId: '511226301219',
    projectId: 'the-clinical-app',
    authDomain: 'the-clinical-app.firebaseapp.com',
    storageBucket: 'the-clinical-app.firebasestorage.app',
    measurementId: 'G-M5J04DC7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZD5JTAUnJQIlA2INdBFXHTVyiMzefTU',
    appId: '1:511226301219:android:940d7f16cc88be83b51a96',
    messagingSenderId: '511226301219',
    projectId: 'the-clinical-app',
    storageBucket: 'the-clinical-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5lBMx9N24_mNb_TTl4dhpx1Vc9UWkng',
    appId: '1:511226301219:ios:ad2185311dc821dbb51a96',
    messagingSenderId: '511226301219',
    projectId: 'the-clinical-app',
    storageBucket: 'the-clinical-app.firebasestorage.app',
    iosBundleId: 'com.example.tastyBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh5lBMx9N24_mNb_TTl4dhpx1Vc9UWkng',
    appId: '1:511226301219:ios:ad2185311dc821dbb51a96',
    messagingSenderId: '511226301219',
    projectId: 'the-clinical-app',
    storageBucket: 'the-clinical-app.firebasestorage.app',
    iosBundleId: 'com.example.tastyBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIokGvom38yovmGozDiidr5RtOOomZ2is',
    appId: '1:511226301219:web:2b5e2c24c1227a28b51a96',
    messagingSenderId: '511226301219',
    projectId: 'the-clinical-app',
    authDomain: 'the-clinical-app.firebaseapp.com',
    storageBucket: 'the-clinical-app.firebasestorage.app',
    measurementId: 'G-GJBFQP7T8Z',
  );

}